version: '3.1'

services:
    go_micro:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ../../internal:/go_micro
        working_dir: /go_micro
        labels:
            - "domains=certificate-check.local"

    vva-docker-hoster:
        container_name: 'docker-hoster-go_micro'
        build:
            context: docker-hoster
            dockerfile: Dockerfile
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            - /etc/hosts:/tmp/hosts
