version: '3.1'

services:
    go_micro:
        build:
            context: app
            dockerfile: Dockerfile
        volumes:
            - ../:/go_micro
        working_dir: /go_micro
        labels:
            - "domains=certificate-check.local"

